# Generated by Django 4.1.1 on 2023-12-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gazete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(default='Bayram Bayramov', max_length=100)),
                ('cover', models.ImageField(upload_to='cover/%Y/%m/')),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='document/%Y/%m/')),
                ('gazete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tst.gazete')),
            ],
        ),
    ]
