# Generated by Django 4.1.1 on 2023-12-29 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='document/%Y/%m/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Gazete',
            new_name='Tst',
        ),
        migrations.DeleteModel(
            name='Sayfa',
        ),
        migrations.AddField(
            model_name='page',
            name='Tst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tst.tst'),
        ),
    ]
